import React from 'react'
import { Check, PackagePlus, ArrowRight } from 'lucide-react'
import { farmers } from '../data/mockData'

export default function Aggregation({ setPage }) {
  const [selected,setSelected] = React.useState([1,2,3])
  const toggle = id => setSelected(s => s.includes(id) ? s.filter(x=>x!==id) : [...s,id])
  const total = farmers.filter(f=>selected.includes(f.id)).reduce((a,b)=>a+b.quantity,0)
  return <div className="mx-auto max-w-7xl px-5 py-8 lg:px-8"><p className="section-label">Supply aggregation</p><h1 className="mt-2 text-3xl font-black">Build one marketable lot</h1><p className="mt-1 text-sm text-black/50">Combine nearby farmers to meet the buyer's bulk requirement and reduce transport cost per kg.</p><div className="mt-7 grid gap-6 lg:grid-cols-[1fr_.75fr]"><div className="space-y-3">{farmers.map(f=><button key={f.id} onClick={()=>toggle(f.id)} className={`paper-card flex w-full items-center gap-4 p-4 text-left ${selected.includes(f.id)?'border-olive/40 bg-olive/5':''}`}><div className={`grid h-9 w-9 shrink-0 place-items-center rounded-full border ${selected.includes(f.id)?'border-olive bg-olive text-white':'border-black/10'}`}>{selected.includes(f.id)?<Check size={17}/>:<span className="text-xs">{f.id}</span>}</div><div className="flex-1"><p className="font-bold">{f.name}</p><p className="mt-1 text-xs text-black/45">{f.location} • {f.crop}</p></div><b>{f.quantity.toLocaleString()} kg</b></button>)}</div><div className="paper-card h-fit p-6"><PackagePlus className="text-terracotta"/><p className="section-label mt-5">Consolidated lot</p><p className="mt-1 text-3xl font-black">{total.toLocaleString()} kg</p><p className="mt-1 text-sm text-black/50">{selected.length} farmers selected</p><div className="mt-5 rounded-xl bg-paper p-4 text-sm"><div className="flex justify-between"><span className="text-black/50">Buyer target</span><b>5,000 kg</b></div><div className="mt-2 flex justify-between"><span className="text-black/50">Shortfall</span><b>{Math.max(0,5000-total).toLocaleString()} kg</b></div><div className="mt-2 flex justify-between"><span className="text-black/50">Est. transport saving</span><b className="text-olive">₹4,250</b></div></div><button disabled={total===0} onClick={()=>setPage('logistics')} className="btn-primary mt-5 w-full disabled:cursor-not-allowed disabled:opacity-40">Optimize transport <ArrowRight size={16}/></button></div></div></div>
}
