import React from 'react'
import { ArrowLeft, Send, MessageCircle, IndianRupee, BadgeCheck } from 'lucide-react'
export default function Chat({product,role,setPage}){
  const [messages,setMessages]=React.useState([{from:'seller',text:`Hello! The listed price for ${product?.crop||'this crop'} is ₹${product?.price||28}/kg. You can send an offer if you want to negotiate.`}])
  const [text,setText]=React.useState('')
  const [offerPrice,setOfferPrice]=React.useState(product?.price?Math.max(1,product.price-1):27)
  const [offerQty,setOfferQty]=React.useState(1000)
  const send=e=>{e.preventDefault();if(!text.trim())return;setMessages([...messages,{from:role==='buyer'?'buyer':'seller',text:text.trim()}]);setText('')}
  const sendOffer=()=>setMessages([...messages,{from:'buyer',text:`Offer: ₹${offerPrice}/kg for ${Number(offerQty).toLocaleString()} kg`,offer:true}])
  return <div className="mx-auto max-w-3xl px-3 py-5 sm:px-5 sm:py-8 lg:px-8"><button onClick={()=>setPage('product')} className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-black/45"><ArrowLeft size={16}/> Back to product</button><div className="overflow-hidden rounded-[22px] border sm:rounded-[30px] border-black/5 bg-white shadow-sm"><div className="flex items-center gap-3 border-b border-black/5 p-4 sm:p-5"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[#eef5e9] text-2xl">{product?.emoji||'🌾'}</span><div><h1 className="font-black">Price negotiation</h1><p className="text-xs text-black/40">{product?.crop} • {product?.seller}</p></div><BadgeCheck className="ml-auto text-[#3b7a48]"/></div>{role==='buyer'&&<div className="grid gap-3 border-b border-black/5 bg-[#fffdf7] p-4 sm:grid-cols-[1fr_1fr_auto]"><label><span className="field-label">Offer ₹/kg</span><input type="number" value={offerPrice} onChange={e=>setOfferPrice(e.target.value)} className="input-field"/></label><label><span className="field-label">Quantity kg</span><input type="number" value={offerQty} onChange={e=>setOfferQty(e.target.value)} className="input-field"/></label><button onClick={sendOffer} className="btn-secondary self-end !py-3"><IndianRupee size={16}/> Send offer</button></div>}<div className="min-h-[280px] bg-[#f7f8f4] p-4 sm:min-h-[330px] sm:p-5"><p className="mb-5 text-center text-[10px] font-bold uppercase tracking-wider text-black/30">Chat is only for price negotiation</p><div className="space-y-3">{messages.map((m,i)=><div key={i} className={`flex ${m.from==='buyer'?'justify-end':'justify-start'}`}><div className={`max-w-[80%] rounded-2xl px-4 py-3 text-sm leading-6 ${m.from==='buyer'?'bg-[#2f6f3e] text-white':'bg-white text-black/70 shadow-sm'} ${m.offer?'font-black':''}`}>{m.text}</div></div>)}</div></div><form onSubmit={send} className="flex gap-2 border-t border-black/5 p-3 sm:p-4"><input value={text} onChange={e=>setText(e.target.value)} placeholder="Write a message about the price..." className="input-field flex-1"/><button className="btn-primary !px-4"><Send size={17}/></button></form></div></div>
}
