import React from 'react'
import { Truck, ArrowRight, IndianRupee, MapPinned } from 'lucide-react'
import MapPanel from '../components/MapPanel'

export default function Logistics() {
  const traditional = 9800
  const optimized = 5550
  return <div className="mx-auto max-w-7xl px-5 py-8 lg:px-8"><p className="section-label">Logistics + final realization</p><h1 className="mt-2 text-3xl font-black">Move the lot efficiently</h1><p className="mt-1 text-sm text-black/50">A prototype route using a consolidated pickup plan.</p><div className="mt-7 grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><div className="paper-card p-4"><div className="mb-4 flex items-center gap-2 px-2"><MapPinned size={18}/><p className="font-bold">Collection → buyer route</p></div><MapPanel/></div><div className="space-y-4"><div className="paper-card p-6"><Truck className="text-terracotta"/><p className="section-label mt-5">Optimized movement</p><p className="mt-1 text-3xl font-black">₹{optimized.toLocaleString()}</p><p className="mt-1 text-sm text-black/50">estimated transport cost</p><div className="mt-5 space-y-2 text-sm"><div className="flex justify-between"><span className="text-black/50">Vehicle</span><b>9-ton truck</b></div><div className="flex justify-between"><span className="text-black/50">Consolidated load</span><b>5,000 kg</b></div><div className="flex justify-between"><span className="text-black/50">Estimated saving</span><b className="text-olive">₹{(traditional-optimized).toLocaleString()}</b></div></div></div><div className="paper-card p-6"><p className="section-label">Farmer realization</p><div className="mt-3 grid grid-cols-2 gap-3"><div className="rounded-xl bg-paper p-4"><p className="text-xs text-black/45">Traditional chain</p><p className="mt-1 text-xl font-black">₹52,500</p></div><div className="rounded-xl bg-olive/10 p-4"><p className="text-xs text-black/45">KisanDirect</p><p className="mt-1 text-xl font-black">₹68,750</p></div></div><div className="mt-4 flex items-center gap-2 rounded-xl bg-terracotta/10 p-3 text-sm font-bold"><IndianRupee size={16}/> +₹16,250 estimated additional realization</div></div></div></div><div className="mt-6 rounded-2xl border border-dashed border-black/15 p-5 text-sm text-black/55"><b className="text-ink">Demo note:</b> route, price and realization values are simulated. Production version can connect government mandi data, weather, live maps, buyer verification and a trained demand model.</div></div>
}
