import React from 'react'
import { Search, MapPin, BadgeCheck, Package, MessageCircle, ShoppingCart } from 'lucide-react'

export default function Marketplace({ role, listings, setPage, openProduct, openChat }) {
  const [q,setQ]=React.useState(()=>{const x=localStorage.getItem('kisan-search')||'';localStorage.removeItem('kisan-search');return x})
  const [crop,setCrop]=React.useState('All')
  const crops=['All',...new Set(listings.map(x=>x.crop))]
  const filtered=listings.filter(x=>(crop==='All'||x.crop===crop)&&`${x.crop} ${x.location} ${x.seller}`.toLowerCase().includes(q.toLowerCase()))
  return <div className="mx-auto max-w-7xl px-3 py-5 sm:px-5 sm:py-8 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Crop marketplace</p><h1 className="mt-2 text-2xl font-black tracking-tight sm:text-3xl">{role==='buyer'?'What do you want to buy?':'Your crops in the marketplace'}</h1><p className="mt-1 text-sm text-black/45">Search by crop, seller or location.</p></div>{role==='farmer'&&<button onClick={()=>setPage('sell')} className="btn-primary">+ Add crop</button>}</div>
  <div className="mt-5 flex flex-col gap-3 rounded-2xl border border-black/5 bg-white p-2.5 shadow-sm sm:mt-6 sm:rounded-3xl sm:p-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-4 top-3.5 text-black/30" size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search wheat, rice, tomato, Karnal..." className="input-field border-0 bg-[#f6f7f2] pl-11"/></div><select value={crop} onChange={e=>setCrop(e.target.value)} className="input-field w-full border-0 bg-[#f6f7f2] sm:w-48">{crops.map(c=><option key={c}>{c}</option>)}</select></div>
  {filtered.length===0?<div className="mt-10 rounded-3xl bg-white p-10 text-center"><h3 className="text-lg font-black sm:text-xl">No crops found</h3><p className="mt-2 text-sm text-black/45">Try another crop or location.</p></div>:<div className="mt-5 grid grid-cols-1 gap-4 sm:mt-6 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(item=><article key={item.id} className="market-card overflow-hidden"><button onClick={()=>openProduct(item)} className="block w-full text-left"><div className="crop-visual relative aspect-[16/10] min-h-0 overflow-hidden sm:aspect-[4/3] lg:aspect-[16/10]">{item.image?<img src={item.image} alt={item.crop} className="absolute inset-0 h-full w-full object-cover"/>:<span className="text-5xl">{item.emoji||'🌾'}</span>}<span className="relative z-10 ml-auto self-start rounded-full bg-white/90 px-3 py-1 text-[10px] font-black shadow-sm">{item.grade||'Farm Grade'}</span></div><div className="p-4 pb-3 sm:p-5 sm:pb-3"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-black sm:text-xl">{item.crop}</h2><p className="mt-1 flex items-center gap-1 text-xs text-black/40"><MapPin size={12}/>{item.location}</p></div><div className="text-right"><p className="text-lg font-black">₹{item.price}/kg</p><p className="text-[10px] text-black/35">listed price</p></div></div><div className="mt-4 flex items-center justify-between rounded-2xl bg-[#f6f7f2] p-3"><span className="flex items-center gap-2 text-xs text-black/45"><Package size={15}/> Available</span><b className="text-sm">{item.quantity}</b></div><div className="mt-4 flex items-center gap-2 text-sm font-bold"><BadgeCheck size={16} className="text-[#3b7a48]"/>{item.seller}</div></div></button><div className="grid grid-cols-2 gap-2 p-4 pt-2 sm:p-5 sm:pt-2">{role==='buyer'?<><button onClick={()=>openChat(item)} className="btn-secondary"><MessageCircle size={15}/> Negotiate</button><button onClick={()=>openProduct(item)} className="btn-primary"><ShoppingCart size={15}/> Buy</button></>:<button onClick={()=>openProduct(item)} className="btn-secondary col-span-2">View listing</button>}</div></article>)}</div>}</div>
}
