import React from 'react'
import { ArrowLeft, MapPin, BadgeCheck, Package, MessageCircle, ShoppingCart, ShieldCheck } from 'lucide-react'

export default function ProductDetails({ product, role, setPage, addToCart, openChat }){
  const [qty,setQty]=React.useState(100)
  if(!product)return <div className="mx-auto max-w-3xl px-5 py-16 text-center"><h1 className="text-2xl font-black">Choose a crop from the marketplace</h1><button onClick={()=>setPage('marketplace')} className="btn-primary mt-5">Browse crops</button></div>
  const available=parseInt(String(product.quantity).replace(/,/g,''))||1000
  const total=Number(product.price)*Number(qty)
  return <div className="mx-auto max-w-6xl px-3 py-5 sm:px-5 sm:py-8 lg:px-8"><button onClick={()=>setPage('marketplace')} className="mb-5 inline-flex items-center gap-2 text-sm font-bold text-black/45"><ArrowLeft size={16}/> Back to marketplace</button><div className="grid gap-4 sm:gap-6 lg:grid-cols-[.95fr_1.05fr]"><div className="relative aspect-[4/3] min-h-0 overflow-hidden rounded-[22px] bg-gradient-to-br from-[#edf6e9] to-[#fff3dc] sm:rounded-[30px] lg:aspect-auto lg:min-h-[460px]">{product.image?<img src={product.image} alt={product.crop} className="absolute inset-0 h-full w-full object-cover"/>:<div className="grid h-full min-h-[260px] place-items-center sm:min-h-[360px]"><span className="text-6xl sm:text-8xl">{product.emoji||'🌾'}</span></div>}</div><div className="rounded-[22px] border border-black/5 bg-white p-4 sm:rounded-[30px] sm:p-8"><span className="rounded-full bg-[#edf5e9] px-3 py-1.5 text-xs font-black text-[#2f6f3e]">{product.grade||'Farm Grade'}</span><h1 className="mt-4 text-3xl font-black sm:text-4xl">{product.crop}</h1><p className="mt-2 flex items-center gap-2 text-sm text-black/45"><MapPin size={15}/>{product.location}</p><div className="mt-6 flex items-end gap-2"><span className="text-3xl font-black">₹{product.price}</span><span className="pb-1 text-sm text-black/40">per kg</span></div><div className="mt-6 grid grid-cols-1 gap-3 min-[380px]:grid-cols-2"><Info icon={<Package/>} l="Available" v={product.quantity}/><Info icon={<BadgeCheck/>} l="Seller" v={product.seller}/></div><p className="mt-6 text-sm leading-7 text-black/55">{product.description||'Fresh farm produce available for bulk purchase. Contact the seller through negotiation chat if you want to discuss the listed price.'}</p>{role==='buyer'?<><div className="mt-6"><span className="field-label">Quantity to buy (kg)</span><input min="1" max={available} type="number" value={qty} onChange={e=>setQty(Math.max(1,Number(e.target.value)))} className="input-field"/></div><div className="mt-4 flex flex-wrap items-center justify-between gap-2 rounded-2xl bg-[#f6f7f2] p-4"><span className="text-sm text-black/45">Estimated total</span><b className="text-xl">₹{total.toLocaleString()}</b></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><button onClick={()=>openChat(product)} className="btn-secondary !py-3.5"><MessageCircle size={17}/> Negotiate price</button><button onClick={()=>addToCart(product,qty)} className="btn-primary !py-3.5"><ShoppingCart size={17}/> Add to cart</button></div><p className="mt-4 flex items-center gap-2 text-xs text-black/40"><ShieldCheck size={14}/> Prototype checkout — no real payment is processed.</p></>:<div className="mt-6 rounded-2xl bg-[#edf5e9] p-4 text-sm text-[#315c3b]">This is how buyers see your crop listing.</div>}</div></div></div>
}
function Info({icon,l,v}){return <div className="rounded-2xl bg-[#f7f8f4] p-4"><span className="text-[#3b7a48]">{React.cloneElement(icon,{size:17})}</span><p className="mt-3 text-[10px] uppercase tracking-wider text-black/35">{l}</p><b className="mt-1 block text-sm">{v}</b></div>}
