import React from 'react'
import { ClipboardPlus, MapPin, CalendarDays } from 'lucide-react'
import { buyerRequirements as demo } from '../data/mockData'

export default function Requirements({ role, requirements, setRequirements, setPage }) {
  const [show,setShow] = React.useState(false)
  const [form,setForm] = React.useState({crop:'Wheat',quantity:5000,location:'Delhi',price:28,date:'15 Sep 2026'})
  const all=[...requirements,...demo]
  const submit=e=>{e.preventDefault();setRequirements([{id:`req-${Date.now()}`,buyer:'Your Business',...form},...requirements]);setShow(false)}
  return <div className="mx-auto max-w-7xl px-5 py-8 lg:px-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">Buyer demand</p><h1 className="mt-2 text-3xl font-black tracking-tight">Bulk requirements</h1><p className="mt-1 text-sm text-black/45">See what buyers need, or post a requirement in seconds.</p></div>{role==='buyer'&&<button onClick={()=>setShow(true)} className="btn-primary"><ClipboardPlus size={17}/> Post requirement</button>}</div>{show&&<form onSubmit={submit} className="mt-6 grid gap-4 rounded-3xl border border-black/5 bg-white p-5 sm:grid-cols-2 lg:grid-cols-5"><Field label="Crop" value={form.crop} onChange={v=>setForm({...form,crop:v})}/><Field label="Quantity (kg)" type="number" value={form.quantity} onChange={v=>setForm({...form,quantity:v})}/><Field label="Delivery city" value={form.location} onChange={v=>setForm({...form,location:v})}/><Field label="Target ₹/kg" type="number" value={form.price} onChange={v=>setForm({...form,price:v})}/><div className="flex items-end"><button className="btn-primary w-full">Publish</button></div></form>}<div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{all.map(r=><div key={r.id} className="market-card p-5"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold text-[#2f6f3e]">{r.buyer}</p><h2 className="mt-1 text-xl font-black">Needs {r.crop}</h2></div><span className="rounded-full bg-[#fff2d3] px-2.5 py-1 text-[10px] font-black text-[#8b641b]">Open</span></div><div className="mt-5 grid grid-cols-2 gap-2"><Info l="Quantity" v={`${Number(r.quantity).toLocaleString()} kg`}/><Info l="Target price" v={`₹${r.price}/kg`}/></div><p className="mt-4 flex items-center gap-2 text-xs text-black/45"><MapPin size={14}/>{r.location}</p><p className="mt-2 flex items-center gap-2 text-xs text-black/45"><CalendarDays size={14}/>Required by {r.date}</p><button onClick={()=>setPage('marketplace')} className="btn-secondary mt-5 w-full">View matching sellers</button></div>)}</div></div>
}
function Field({label,value,onChange,type='text'}) {return <label><span className="field-label">{label}</span><input className="input-field" required type={type} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Info({l,v}) {return <div className="rounded-2xl bg-[#f6f7f2] p-3"><p className="text-[10px] uppercase tracking-wider text-black/35">{l}</p><b className="mt-1 block text-sm">{v}</b></div>}
